### ISSUE TITLE
Constantly re-directing after successful authentication 

### ISSUE THREAD

**Issue by edas-smith** [awslabs/cognito-at-edge#54]
Hello guys,

Currently i'm hitting with too many redirects issue, even after successful authentication with google.

My setup involves using Cognito, which allows to login via google.

I have configured my Cognito callBackUrls same as my site url https://xyz.test.com.

Has anyone had anything similar know why this could be?

Thank you!

**Comment by nagendrakumar02** [comment]
I am trying to use a SAML provider, How are you able to pass different id providers from the code?

**Comment by edas-smith** [comment]
Basically using the same code as you @nagendrakumar02 https://github.com/awslabs/cognito-at-edge/issues/56

**Comment by jeandek** [comment]
Hi @edas-smith ,

If that is not already the case, I suggest upgrading to the latest version of cognito-at-edge (1.3.1) as it fixes an issue with cookie parsing that could cause redirection loops in some cases.

If you are building a web app using AWS Amplify, you may want to try to authenticate to the Cognito userpool from within your app using `Auth.federatedSignIn()`. That would allow you to determine if the issue comes from your user pool configuration or from the Lambda@Edge function.

**Comment by edas-smith** [comment]
Hello @jeandek I have checked and it definitely is up to date. I think the error will likely be on my end somewhere, rather than an actual issue. Will close.
